server:
  port: 8080
spring:
  application:
    name: ApiGateway

  cloud:
    gateway:
      routes:
        - id: UserService
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**
        - id: TaskService
          uri: http://localhost:8082/
          predicates:
            - Path=/tasks/**

